-- INSERT de elementos deportivos reales extraídos de ABRs050_ FORMATO CRD F(1).xlsx
-- Se usó DESCRIPCIÓN como nombre/descripcion y la columna N° como cantidad.
-- Si ya tenías el seed demo, esta línea lo desactiva para que no se mezclen elementos de prueba con inventario real.
BEGIN;
UPDATE "elementos_deportivos" SET "activo" = false, "actualizadoEn" = NOW() WHERE "codigo" IN ('BAL-FUT-001', 'BAL-VOL-001', 'RAQ-TEN-001', 'CON-001', 'PET-001', 'PLA-001', 'ARO-001', 'VOL-BAD-001');

INSERT INTO "elementos_deportivos"
("id", "nombre", "codigo", "descripcion", "marca", "color", "categoria", "cantidadTotal", "cantidadDisponible", "activo", "icono", "creadoEn", "actualizadoEn")
VALUES
('ed_real_001', 'PLATILLOS DE SEÑALIZACION', 'CRD-REAL-001', 'PLATILLOS DE SEÑALIZACION', NULL, NULL, 'Entrenamiento', 93, 93, true, '🔶', NOW(), NOW()),
('ed_real_002', 'CONOS GRANDES DE SEÑALIZACION', 'CRD-REAL-002', 'CONOS GRANDES DE SEÑALIZACION', NULL, NULL, 'Entrenamiento', 50, 50, true, '🔶', NOW(), NOW()),
('ed_real_003', 'CONOS DE SEÑALIZACION INDUSTRIALES', 'CRD-REAL-003', 'CONOS DE SEÑALIZACION INDUSTRIALES', NULL, NULL, 'Entrenamiento', 40, 40, true, '🔶', NOW(), NOW()),
('ed_real_004', 'HEXAGONOS', 'CRD-REAL-004', 'HEXAGONOS', NULL, NULL, 'Entrenamiento', 50, 50, true, '🏅', NOW(), NOW()),
('ed_real_005', 'AROS ULA ULA', 'CRD-REAL-005', 'AROS ULA ULA', NULL, NULL, 'Aros', 60, 60, true, '⭕', NOW(), NOW()),
('ed_real_006', 'AROS PLANOS', 'CRD-REAL-006', 'AROS PLANOS', NULL, NULL, 'Aros', 50, 50, true, '⭕', NOW(), NOW()),
('ed_real_007', 'PARACAIDAS DE RESISTENCIA', 'CRD-REAL-007', 'PARACAIDAS DE RESISTENCIA', NULL, NULL, 'Entrenamiento', 5, 5, true, '🏅', NOW(), NOW()),
('ed_real_008', 'ESTACA DE SEÑALIZACION MEDIANA', 'CRD-REAL-008', 'ESTACA DE SEÑALIZACION MEDIANA', NULL, NULL, 'Entrenamiento', 36, 36, true, '🔶', NOW(), NOW()),
('ed_real_009', 'MALLAS DE MICRO FUTBOL (PARES)', 'CRD-REAL-009', 'MALLAS DE MICRO FUTBOL (PARES)', NULL, NULL, 'Mallas y porterías', 3, 3, true, '🥅', NOW(), NOW()),
('ed_real_010', 'VALLAS DE PLASTICO PEQUEÑAS', 'CRD-REAL-010', 'VALLAS DE PLASTICO PEQUEÑAS', NULL, NULL, 'Entrenamiento', 10, 10, true, '🏅', NOW(), NOW()),
('ed_real_011', 'BASE PARA ESTACAS COLOR NARANJA', 'CRD-REAL-011', 'BASE PARA ESTACAS COLOR NARANJA', NULL, NULL, 'Entrenamiento', 10, 10, true, '🔶', NOW(), NOW()),
('ed_real_012', 'MALLA DE PING PONG', 'CRD-REAL-012', 'MALLA DE PING PONG', NULL, NULL, 'Mallas y porterías', 1, 1, true, '🥅', NOW(), NOW()),
('ed_real_013', 'MALLA DE TENIS', 'CRD-REAL-013', 'MALLA DE TENIS', NULL, NULL, 'Raquetas y bádminton', 1, 1, true, '🎾', NOW(), NOW()),
('ed_real_014', 'MALLA FUTBOL TENIS', 'CRD-REAL-014', 'MALLA FUTBOL TENIS', NULL, NULL, 'Raquetas y bádminton', 1, 1, true, '🎾', NOW(), NOW()),
('ed_real_015', 'MALLA GRANDE DE TENIS', 'CRD-REAL-015', 'MALLA GRANDE DE TENIS', NULL, NULL, 'Raquetas y bádminton', 1, 1, true, '🎾', NOW(), NOW()),
('ed_real_016', 'MALLA DE BALONCESTO " PAR"', 'CRD-REAL-016', 'MALLA DE BALONCESTO " PAR"', NULL, NULL, 'Balones', 1, 1, true, '🏀', NOW(), NOW()),
('ed_real_017', 'RODILLOS DE BICICLETA COMPLETOS', 'CRD-REAL-017', 'RODILLOS DE BICICLETA COMPLETOS', NULL, NULL, 'Inventario real CRD', 4, 4, true, '🏅', NOW(), NOW()),
('ed_real_018', 'RODILLOS DOBLE MARCA VENZO', 'CRD-REAL-018', 'RODILLOS DOBLE MARCA VENZO', NULL, NULL, 'Inventario real CRD', 4, 4, true, '🏅', NOW(), NOW()),
('ed_real_019', 'DESLIZADORES DE PATINAJE CON ESTUCHE', 'CRD-REAL-019', 'DESLIZADORES DE PATINAJE CON ESTUCHE', NULL, NULL, 'Inventario real CRD', 3, 3, true, '🏅', NOW(), NOW()),
('ed_real_020', 'BALONES DE PILATES', 'CRD-REAL-020', 'BALONES DE PILATES', NULL, NULL, 'Balones', 9, 9, true, '⚽', NOW(), NOW()),
('ed_real_021', 'VALLAS DE CAMPO DE SALTO', 'CRD-REAL-021', 'VALLAS DE CAMPO DE SALTO', NULL, NULL, 'Entrenamiento', 10, 10, true, '🏅', NOW(), NOW()),
('ed_real_022', 'CAJONES', 'CRD-REAL-022', 'CAJONES', NULL, NULL, 'Inventario real CRD', 3, 3, true, '🏅', NOW(), NOW()),
('ed_real_023', 'ESTACAS CON PUNTILLA DE COLORES MARCA MIYAGY', 'CRD-REAL-023', 'ESTACAS CON PUNTILLA DE COLORES MARCA MIYAGY', NULL, NULL, 'Entrenamiento', 27, 27, true, '🔶', NOW(), NOW()),
('ed_real_024', 'STICKS DE HOCKEY MARCA STREET HOCKEY', 'CRD-REAL-024', 'STICKS DE HOCKEY MARCA STREET HOCKEY', NULL, NULL, 'Deportes específicos', 18, 18, true, '🏅', NOW(), NOW()),
('ed_real_025', 'PETOS', 'CRD-REAL-025', 'PETOS', NULL, NULL, 'Inventario real CRD', 27, 27, true, '🏅', NOW(), NOW()),
('ed_real_026', 'ESCALERAS DE COORDINACION', 'CRD-REAL-026', 'ESCALERAS DE COORDINACION', NULL, NULL, 'Entrenamiento', 6, 6, true, '🏅', NOW(), NOW()),
('ed_real_027', 'BASE INESTABLE', 'CRD-REAL-027', 'BASE INESTABLE', NULL, NULL, 'Inventario real CRD', 1, 1, true, '🏅', NOW(), NOW()),
('ed_real_028', 'VALLAS PARA FUTBOL TENIS MARCA WILSON', 'CRD-REAL-028', 'VALLAS PARA FUTBOL TENIS MARCA WILSON', NULL, NULL, 'Raquetas y bádminton', 3, 3, true, '🎾', NOW(), NOW()),
('ed_real_029', 'CASCOS INDUSTRIALES COLOR BLANCO', 'CRD-REAL-029', 'CASCOS INDUSTRIALES COLOR BLANCO', NULL, NULL, 'Escalada', 10, 10, true, '🧗', NOW(), NOW()),
('ed_real_030', 'DISCOS DE ULTIMATE', 'CRD-REAL-030', 'DISCOS DE ULTIMATE', NULL, NULL, 'Deportes específicos', 3, 3, true, '🏅', NOW(), NOW()),
('ed_real_031', 'CUERDAS PARA SALTAR', 'CRD-REAL-031', 'CUERDAS PARA SALTAR', NULL, NULL, 'Inventario real CRD', 17, 17, true, '🏅', NOW(), NOW()),
('ed_real_032', 'ESCUDOS PARA RUGBY', 'CRD-REAL-032', 'ESCUDOS PARA RUGBY', NULL, NULL, 'Deportes específicos', 2, 2, true, '🏅', NOW(), NOW()),
('ed_real_033', 'PAQUETE X 5 BANDAS ELÁSTICAS', 'CRD-REAL-033', 'PAQUETE X 5 BANDAS ELÁSTICAS', NULL, NULL, 'Inventario real CRD', 4, 4, true, '🏅', NOW(), NOW()),
('ed_real_034', 'CAJONES DE STEP MARCA MIYAGI', 'CRD-REAL-034', 'CAJONES DE STEP MARCA MIYAGI', NULL, NULL, 'Inventario real CRD', 5, 5, true, '🏅', NOW(), NOW()),
('ed_real_035', 'BOMBA DE INFLAR BALONES', 'CRD-REAL-035', 'BOMBA DE INFLAR BALONES', NULL, NULL, 'Balones', 3, 3, true, '⚽', NOW(), NOW()),
('ed_real_036', 'CRONOMETRO', 'CRD-REAL-036', 'CRONOMETRO', NULL, NULL, 'Inventario real CRD', 4, 4, true, '⏱️', NOW(), NOW()),
('ed_real_037', 'KIT DE BADMINTON', 'CRD-REAL-037', 'KIT DE BADMINTON', NULL, NULL, 'Raquetas y bádminton', 10, 10, true, '🎾', NOW(), NOW()),
('ed_real_038', 'BALON DE BASQUETBOL MARCA GOLTY # 7', 'CRD-REAL-038', 'BALON DE BASQUETBOL MARCA GOLTY # 7', NULL, NULL, 'Balones', 48, 48, true, '🏀', NOW(), NOW()),
('ed_real_039', 'BALON DE BASQUETBOL MARCA GOLTY # 6', 'CRD-REAL-039', 'BALON DE BASQUETBOL MARCA GOLTY # 6', NULL, NULL, 'Balones', 26, 26, true, '🏀', NOW(), NOW()),
('ed_real_040', 'BALON DE BASQUETBOL MARCA MOLTEN # 7', 'CRD-REAL-040', 'BALON DE BASQUETBOL MARCA MOLTEN # 7', NULL, NULL, 'Balones', 42, 42, true, '🏀', NOW(), NOW()),
('ed_real_041', 'BALON DE BASQUETBOL MARCA MOLTEN # 6', 'CRD-REAL-041', 'BALON DE BASQUETBOL MARCA MOLTEN # 6', NULL, NULL, 'Balones', 26, 26, true, '🏀', NOW(), NOW()),
('ed_real_042', 'BALON DE BASQUETBOL MARCA MOLTEN # 5', 'CRD-REAL-042', 'BALON DE BASQUETBOL MARCA MOLTEN # 5', NULL, NULL, 'Balones', 10, 10, true, '🏀', NOW(), NOW()),
('ed_real_043', 'BALON DE BALON MANO MARCA MOLTEN # 3', 'CRD-REAL-043', 'BALON DE BALON MANO MARCA MOLTEN # 3', NULL, NULL, 'Balones', 10, 10, true, '⚽', NOW(), NOW()),
('ed_real_044', 'BALON DE BASQUETBOL MARCA SPALDING # 7', 'CRD-REAL-044', 'BALON DE BASQUETBOL MARCA SPALDING # 7', NULL, NULL, 'Balones', 2, 2, true, '🏀', NOW(), NOW()),
('ed_real_045', 'BALON DE BASQUETBOL MARCA SPALDING # 6', 'CRD-REAL-045', 'BALON DE BASQUETBOL MARCA SPALDING # 6', NULL, NULL, 'Balones', 6, 6, true, '🏀', NOW(), NOW()),
('ed_real_046', 'BALON PARA RUGBY', 'CRD-REAL-046', 'BALON PARA RUGBY', NULL, NULL, 'Balones', 4, 4, true, '⚽', NOW(), NOW()),
('ed_real_047', 'BALON MEDICINAL DE 5 KL COLOR ROJO', 'CRD-REAL-047', 'BALON MEDICINAL DE 5 KL COLOR ROJO', NULL, NULL, 'Balones', 3, 3, true, '⚽', NOW(), NOW()),
('ed_real_048', 'BALON MEDICINAL DE 2 KL COLOR NEGRO CON AMARILLO', 'CRD-REAL-048', 'BALON MEDICINAL DE 2 KL COLOR NEGRO CON AMARILLO', NULL, NULL, 'Balones', 4, 4, true, '⚽', NOW(), NOW()),
('ed_real_049', 'BALAS DE LANZAMIENTO OLIMPICO DE 5 KL', 'CRD-REAL-049', 'BALAS DE LANZAMIENTO OLIMPICO DE 5 KL', NULL, NULL, 'Inventario real CRD', 5, 5, true, '🏅', NOW(), NOW()),
('ed_real_050', 'DISCO DE LANZAMIENTO OLIMPICO', 'CRD-REAL-050', 'DISCO DE LANZAMIENTO OLIMPICO', NULL, NULL, 'Inventario real CRD', 9, 9, true, '🏅', NOW(), NOW()),
('ed_real_051', 'EQUIPO PARA TRX MARCA SPORT FITNESS', 'CRD-REAL-051', 'EQUIPO PARA TRX MARCA SPORT FITNESS', NULL, NULL, 'Inventario real CRD', 8, 8, true, '🏅', NOW(), NOW()),
('ed_real_052', 'SILLA ERGONOMICA', 'CRD-REAL-052', 'SILLA ERGONOMICA', NULL, NULL, 'Mobiliario y apoyo', 2, 2, true, '🏅', NOW(), NOW()),
('ed_real_053', 'ESTANTE METALICO CUATRO PUESTOS', 'CRD-REAL-053', 'ESTANTE METALICO CUATRO PUESTOS', NULL, NULL, 'Mobiliario y apoyo', 1, 1, true, '🏅', NOW(), NOW()),
('ed_real_054', 'MESA TUBO METALICO', 'CRD-REAL-054', 'MESA TUBO METALICO', NULL, NULL, 'Mobiliario y apoyo', 2, 2, true, '🏅', NOW(), NOW()),
('ed_real_055', 'ARCHIVADOR TRES PUESTOS', 'CRD-REAL-055', 'ARCHIVADOR TRES PUESTOS', NULL, NULL, 'Mobiliario y apoyo', 1, 1, true, '🏅', NOW(), NOW()),
('ed_real_056', 'LOCKERS DE 4 SERVICIOS', 'CRD-REAL-056', 'LOCKERS DE 4 SERVICIOS', NULL, NULL, 'Mobiliario y apoyo', 1, 1, true, '🏅', NOW(), NOW()),
('ed_real_057', 'BASCULA DE PISO SOHENLE', 'CRD-REAL-057', 'BASCULA DE PISO SOHENLE', NULL, NULL, 'Mobiliario y apoyo', 1, 1, true, '🏅', NOW(), NOW()),
('ed_real_058', 'RAQUETA TENIS PRINCE TITANIO', 'CRD-REAL-058', 'RAQUETA TENIS PRINCE TITANIO', NULL, NULL, 'Raquetas y bádminton', 3, 3, true, '🎾', NOW(), NOW()),
('ed_real_059', 'MALLA DIVISORIA CAMPO DEPORTIVO. 37 MTS LARGO X 5 MTS ALTO. NYLON 2', 'CRD-REAL-059', 'MALLA DIVISORIA CAMPO DEPORTIVO. 37 MTS LARGO X 5 MTS ALTO. NYLON 2', NULL, NULL, 'Mallas y porterías', 1, 1, true, '🥅', NOW(), NOW()),
('ed_real_060', 'ESQUELETO HUMANO, ADULTO MARCA: NASCO DE PROCET SCIENTEFIC REF. 00101-6102002. ALTURA 6-1/2 PIES', 'CRD-REAL-060', 'ESQUELETO HUMANO, ADULTO MARCA: NASCO DE PROCET SCIENTEFIC REF. 00101-6102002. ALTURA 6-1/2 PIES', NULL, NULL, 'Inventario real CRD', 1, 1, true, '🏅', NOW(), NOW()),
('ed_real_061', 'RAQUETA EN ALUMINIO MARCA WESTON, AGARRE GENERICO.', 'CRD-REAL-061', 'RAQUETA EN ALUMINIO MARCA WESTON, AGARRE GENERICO.', NULL, NULL, 'Raquetas y bádminton', 18, 18, true, '🎾', NOW(), NOW()),
('ed_real_062', 'TABLERO ACRILICO PARA ESCRITURA BORRABLE DE 1,20 X 2,40 MTS.', 'CRD-REAL-062', 'TABLERO ACRILICO PARA ESCRITURA BORRABLE DE 1,20 X 2,40 MTS.', NULL, NULL, 'Mobiliario y apoyo', 1, 1, true, '🏅', NOW(), NOW()),
('ed_real_063', 'MINICOMPRESOR PARA INFLAR BALONES', 'CRD-REAL-063', 'MINICOMPRESOR PARA INFLAR BALONES', NULL, NULL, 'Balones', 1, 1, true, '⚽', NOW(), NOW()),
('ed_real_064', 'ESTANTE METALICO Y MADERA DE 2,00 X 0,92 X 0,60 MTS, ENCHAPADO EN MADERA TRIPLEX', 'CRD-REAL-064', 'ESTANTE METALICO Y MADERA DE 2,00 X 0,92 X 0,60 MTS, ENCHAPADO EN MADERA TRIPLEX', NULL, NULL, 'Mobiliario y apoyo', 6, 6, true, '🏅', NOW(), NOW()),
('ed_real_065', 'CARRO PORTA BALONES METALICO REFORZADO DE REJILLA CON RUEDAS GIRATORIAS, PUERTA SUPERIOR PROVISTA DE CIERRE, CAPACIDAD 20/30 BALONES; DIMENSIONES 80*65*63 CM.', 'CRD-REAL-065', 'CARRO PORTA BALONES METALICO REFORZADO DE REJILLA CON RUEDAS GIRATORIAS, PUERTA SUPERIOR PROVISTA DE CIERRE, CAPACIDAD 20/30 BALONES; DIMENSIONES 80*65*63 CM.', NULL, NULL, 'Balones', 3, 3, true, '⚽', NOW(), NOW()),
('ed_real_066', 'STICK DE HOCKEY', 'CRD-REAL-066', 'STICK DE HOCKEY', NULL, NULL, 'Deportes específicos', 3, 3, true, '🏅', NOW(), NOW()),
('ed_real_067', 'BALON DE BALONCESTO MOLTEN #5 Y #6', 'CRD-REAL-067', 'BALON DE BALONCESTO MOLTEN #5 Y #6', NULL, NULL, 'Balones', 92, 92, true, '🏀', NOW(), NOW()),
('ed_real_068', 'PELOTAS DE TENIS', 'CRD-REAL-068', 'PELOTAS DE TENIS', NULL, NULL, 'Raquetas y bádminton', 80, 80, true, '🎾', NOW(), NOW()),
('ed_real_069', 'RAQUETA DE SQUAT', 'CRD-REAL-069', 'RAQUETA DE SQUAT', NULL, NULL, 'Raquetas y bádminton', 8, 8, true, '🎾', NOW(), NOW()),
('ed_real_070', 'DESCANSA PIES', 'CRD-REAL-070', 'DESCANSA PIES', NULL, NULL, 'Mobiliario y apoyo', 1, 1, true, '🏅', NOW(), NOW()),
('ed_real_071', 'TESTIGOS', 'CRD-REAL-071', 'TESTIGOS', NULL, NULL, 'Entrenamiento', 32, 32, true, '🏅', NOW(), NOW()),
('ed_real_072', 'AJEDREZ GRANDE PIEZAS', 'CRD-REAL-072', 'AJEDREZ GRANDE PIEZAS', NULL, NULL, 'Juegos', 32, 32, true, '♟️', NOW(), NOW()),
('ed_real_073', 'BALONES DE FUTBOL GOLTY', 'CRD-REAL-073', 'BALONES DE FUTBOL GOLTY', NULL, NULL, 'Balones', 30, 30, true, '⚽', NOW(), NOW()),
('ed_real_074', 'RAQUETAS DE BADMINTON', 'CRD-REAL-074', 'RAQUETAS DE BADMINTON', NULL, NULL, 'Raquetas y bádminton', 8, 8, true, '🎾', NOW(), NOW()),
('ed_real_075', 'RAQUETAS DE TENIS DE CAMPO', 'CRD-REAL-075', 'RAQUETAS DE TENIS DE CAMPO', NULL, NULL, 'Raquetas y bádminton', 35, 35, true, '🎾', NOW(), NOW()),
('ed_real_076', 'JUEGO DE BASE DE BEISBOL DE 5 PIEZAS', 'CRD-REAL-076', 'JUEGO DE BASE DE BEISBOL DE 5 PIEZAS', NULL, NULL, 'Deportes específicos', 3, 3, true, '🏅', NOW(), NOW()),
('ed_real_077', 'PELOTAS DE TENIS PUNTO VERDE SET DE 3', 'CRD-REAL-077', 'PELOTAS DE TENIS PUNTO VERDE SET DE 3', NULL, NULL, 'Raquetas y bádminton', 20, 20, true, '🎾', NOW(), NOW()),
('ed_real_078', 'MARCADOR DEPORTIVO', 'CRD-REAL-078', 'MARCADOR DEPORTIVO', NULL, NULL, 'Inventario real CRD', 4, 4, true, '🏅', NOW(), NOW()),
('ed_real_079', 'CAJA POR 60 OVERGIP TORNAGRIP PARA RAQUETAS', 'CRD-REAL-079', 'CAJA POR 60 OVERGIP TORNAGRIP PARA RAQUETAS', NULL, NULL, 'Raquetas y bádminton', 2, 2, true, '🎾', NOW(), NOW()),
('ed_real_080', 'TARRO DE 6 VOLANTES (GALLOS) BADMINTON', 'CRD-REAL-080', 'TARRO DE 6 VOLANTES (GALLOS) BADMINTON', NULL, NULL, 'Raquetas y bádminton', 6, 6, true, '🎾', NOW(), NOW()),
('ed_real_081', 'PARACAIDAS DE ENTRENAMIENTO (SE REPITE)', 'CRD-REAL-081', 'PARACAIDAS DE ENTRENAMIENTO (SE REPITE)', NULL, NULL, 'Entrenamiento', 8, 8, true, '🏅', NOW(), NOW()),
('ed_real_082', 'BALONES DE VOLEIBOL', 'CRD-REAL-082', 'BALONES DE VOLEIBOL', NULL, NULL, 'Balones', 20, 20, true, '🏐', NOW(), NOW()),
('ed_real_083', 'ARNES DE SEGURIDAD PARA ESCALADA', 'CRD-REAL-083', 'ARNES DE SEGURIDAD PARA ESCALADA', NULL, NULL, 'Escalada', 10, 10, true, '🧗', NOW(), NOW()),
('ed_real_084', 'BALONES FUTBOL SALA', 'CRD-REAL-084', 'BALONES FUTBOL SALA', NULL, NULL, 'Balones', 10, 10, true, '⚽', NOW(), NOW()),
('ed_real_085', 'KIT SLACK LINE', 'CRD-REAL-085', 'KIT SLACK LINE', NULL, NULL, 'Escalada', 3, 3, true, '🏅', NOW(), NOW()),
('ed_real_086', 'CASCO PARA ESCALADA', 'CRD-REAL-086', 'CASCO PARA ESCALADA', NULL, NULL, 'Escalada', 15, 15, true, '🧗', NOW(), NOW())
ON CONFLICT ("codigo") DO UPDATE SET
  "nombre" = EXCLUDED."nombre",
  "descripcion" = EXCLUDED."descripcion",
  "marca" = EXCLUDED."marca",
  "color" = EXCLUDED."color",
  "categoria" = EXCLUDED."categoria",
  "cantidadTotal" = EXCLUDED."cantidadTotal",
  "cantidadDisponible" = EXCLUDED."cantidadDisponible",
  "activo" = true,
  "icono" = EXCLUDED."icono",
  "actualizadoEn" = NOW();
COMMIT;